### ISSUE TITLE
Calculate amount out offchain

### ISSUE THREAD

**Issue by Sotatek-SinhVu** [CrocSwap/sdk#41]
Any suggestions for calculating amount out offchain?

The idea is that we will query some on-chain information (like curve, pool, etc,...), then use them as input data to calculate offchain.

I tried to wrote `CrocImpact` (using typescript) to calculate `baseFlow & quoteFlow` offchain but stuck at `readSlot` method.

**Comment by WuBruno** [comment]
I am still curious about how this could be done. Did you find any ways of doing this? @Sotatek-SinhVu
